# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wcpdtoolbox',
                'doc_host': 'https://doucx.github.io',
                'git_url': 'https://github.com/doucx/wcpdtoolbox',
                'lib_path': 'wcpdtoolbox'},
  'syms': {'wcpdtoolbox.core': {'wcpdtoolbox.core.foo': ('core.html#foo', 'wcpdtoolbox/core.py')}}}
