# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_audio.ipynb.

# %% auto 0
__all__ = ['get_wav_raw', 'get_mp3_raw', 'export_wav', 'play_arr', 'play_tensor']

# %% ../nbs/04_audio.ipynb 3
from .imports import *
from pydub import AudioSegment
import torchaudio

# %% ../nbs/04_audio.ipynb 8
def get_wav_raw(path):
    wav = AudioSegment.from_wav(path).set_frame_rate(32000)
    return np.frombuffer(wav.raw_data, dtype='int16')#,wav.frame_rate

# %% ../nbs/04_audio.ipynb 10
def get_mp3_raw(path: str):
    mp3 = AudioSegment.from_mp3(path).set_frame_rate(32000)
    return np.frombuffer(mp3.raw_data, dtype='int16')#,mp3.frame_rate

# %% ../nbs/04_audio.ipynb 12
def export_wav(arr: np.array, name, rate: int=32000):
    arr.astype(np.int16)
    scipy.io.wavfile.write(name, rate, arr)

# %% ../nbs/04_audio.ipynb 14
def play_arr(arr: np.array,rate: int=32000):
    b = io.BytesIO()
    arr = arr.astype(np.int16)
    export_wav(arr=arr, name=b, rate=rate)
    return AudioSegment.from_wav(b)

# %% ../nbs/04_audio.ipynb 17
def play_tensor(tensor: Tensor, rate: int=32000):
    arr = tensor.detach().cpu().numpy()
    return play_arr(arr, rate=rate)
