# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_data.ipynb.

# %% auto 0
__all__ = ['pick_one']

# %% ../nbs/02_data.ipynb 2
from .imports import *

# %% ../nbs/02_data.ipynb 4
def pick_one(l): return l[random.randint(0, len(l)-1)]
