# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/imports.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/imports.ipynb 1
# 导入需要的包 
import cv2
import graphviz
import gc

from fastcore import *
from fastbook import *
from fastcore.all import *
import fastbook
fastbook.setup_book()
