# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_visualization.ipynb.

# %% auto 0
__all__ = ['GradShowCallback']

# %% ../nbs/03_visualization.ipynb 3
from .imports import *

# %% ../nbs/03_visualization.ipynb 6
class GradShowCallback(Callback):
    def __init__(self, l): self.grad_list = l
    def before_step(self):
        grads = L([to_detach(i.grad.abs().mean()) for i in self.learn.model.parameters()])
        self.grad_list.append(grads)
    
    def after_fit(self):
        name = [name for name, _ in self.learn.model.named_parameters()]
        for name, i in zip(name,array(self.grad_list).T): plt.plot(i, label=name)
        plt.legend()
        plt.show()
